on:
  push:
    branches:
      - main

name: Deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v4

      - name: Set up SSH key and whitelist EC2 IP address
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan ${{ secrets.EC2_PUBLIC_IP }} >> ~/.ssh/known_hosts


      - name: Create .env for dynamically
        env: 
          ENV: ${{ secret.ENV }}
          EC2_USERNAME: ${{ secret.EC2_USERNAME }}
        run: |
          echo "ENV=${ENV}" >> env
          echo "EC2_USERNAME=${EC2_USERNAME}" >> env
      
      -name: copy file to remote server
        env:
          EC2_HOST: ${{ secret.EC2_HOST }}
          EC2_USERNAME: ${{ secret.EC2_USERNAME }}
        run: |
          scp -r ./server ./map ./dashboard $EC2_USERNAME@$EC2_HOST:/home/$EC2_USERNAME/

      -name: Run Bash script To Deploy APP
        env:
          EC2_HOST: ${{ secret.EC2_HOST }}
          EC2_USERNAME: ${{ secret.EC2_USERNAME }}
        run: |
          ssh -o StrictHostKeyChecking=no $EC2_USERNAME@$EC2_HOST "chmod +x ./deploy.sh && ./deploy.sh"

      -name: Clean up SSH key
        if: always()
        run: rm -f ~/.ssh/id_rsa